Repository adalbertobrant/metabolismobasal, pull requests merged in 2020-10, with the labels that each got.

#13 Melhoramento nos links do footer
  index.html
  public/style.css
Labels: hacktoberfest-accepted

#10 Add minor spanish fix
  README_EN.md
  README_ES.md
Labels: hacktoberfest-accepted

#19 Add Code of conduct and licence to the project
  CODE_OF_CONDUCT.md
  LICENSE
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#25 Fix folders structures and fix some file names to improve contributions
  README.md
  locales/en-US/README_EN.md
  locales/es-ES/README_ES.md
  public/scripts/scripts.js
  public/styles/style.css
Labels: hacktoberfest-accepted

#28 add polish translation
  README.md
  locales/pl-PL/README_PL.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, translation

#35 Fix broken PR
  index.html
  index_ES.html
  index_it.html
  public/scripts/scripts.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, help wanted

#34 Add Japanese translation
  locales/ja-JP/README_ja.md
Labels: enhancement, good first issue, hacktoberfest-accepted, translation

#38 CSS Changes, Favicon, Fix IT page
  index.html
  index_ES.html
  index_it.html
  public/styles/style.css
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, help wanted
