Repository adalbertobrant/metabolismobasal, pull requests merged in 2025-06, with the labels that each got.

#63 Update IMC.test.js
  __tests__/Unitary/IMC.test.js
Labels: enhancement

#57 Refactor some function using english and adjust unit test
  __tests__/Unitary/IMC.test.js
  public/scripts/scripts.cjs
Labels: bug

#64 fixing form reliability
  index.html
  indiceCorporal/css/index.css
  indiceCorporal/index.html
  public/pages/index_ES.html
  public/pages/index_en.html
  public/pages/index_it.html
  public/styles/style.css
Labels: enhancement, good first issue

#65 Adicionando calculo de proteínas(em todos os idiomas)
  index.html
  public/pages/index_ES.html
  public/pages/index_en.html
  public/pages/index_it.html
  public/scripts/scripts.cjs
  public/styles/style.css
Labels: bug, enhancement
